import type { Metadata } from "next";
import { Poppins, Kanit } from "next/font/google";
import "@/app/_styles/globals.css";
import { cn } from "@/app/_lib/utils";
import Sidebar from "@/app/_components/sidebar/Sidebar";
import { Texture } from "@/app/_components/ui/Texture";
import { Provider } from "../_context/Provider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-default",
});

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background font-poppins outline-none",
          poppins.variable,
          kanit.variable
        )}
      >
        <div className="mx-auto flex max-w-6xl flex-col px-8 lg:flex-row lg:gap-10 lg:py-24">
          <Provider>
            <Sidebar />
            {children}
            <Texture />
          </Provider>
        </div>
      </body>
    </html>
  );
}
